name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' 

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Stop previous bot instance
        run: pkill -f "python yuk.py" || echo "No previous instance found"

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: nohup python yuk.py &
